# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Theme Wiki"
license = "MIT"
licenselink = "https://github.com/seisman/wiki/blob/master/themes/hugo-theme-wiki/LICENSE.md"
description = "Hugo theme for personal wiki"
homepage = "http://github.com/seisman/wiki"
tags = ["wiki"]
features = []
min_version = "0.22"

[author]
  name = "Dongdong Tian"
  homepage = "http://wiki.seisman.info"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
